apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-backend-config
spec:
  securityPolicy:
    name: boutique-security-policy #policy name is hard coded (could it be done better!!!!)