# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
  setup-build:
    name: skaffold
    runs-on: ubuntu-latest

    #use bash
    defaults:
      run:
        shell: bash
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: projects/351068178296/locations/global/workloadIdentityPools/test-pool-1/providers/test-provider
          service_account: github-test-1@team-3-a.iam.gserviceaccount.com

      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v0.4.0
        with:
          cluster_name: online-shop-cluster
          location: us-central1

          #cache old images
      - name: Cache skaffold image builds & config
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/
          key: fixed

          #install skaffold
      - name: Install skaffold
        uses: hiberbee/github-action-skaffold@1.12.0
        with:
          namespace: 'prod'

      - name: Build + Deploy application to GKE
        timeout-minutes: 30
        run: |
          echo Deploying application
          skaffold config set --global local-cluster false
          skaffold run -f=skaffold.yaml --default-repo=gcr.io/$GOOGLE_CLOUD_PROJECT --namespace=prod
      - name: get pods
        timeout-minutes: 20
        run: |
          kubectl get pods --namespace=prod